# Generated by Django 3.0.6 on 2020-07-16 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FidoFinder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.TextField(default='Age')),
                ('breed', models.TextField(default='Breed')),
                ('color', models.TextField(default='Color')),
                ('date', models.TextField(default='Date')),
                ('gender', models.TextField(default='Gender')),
                ('image', models.TextField(default='Image')),
                ('location', models.TextField(default='Location')),
                ('name', models.TextField(default='Name')),
                ('petid', models.TextField(default='PetID')),
                ('size', models.TextField(default='Size')),
                ('status', models.TextField(default='Status')),
                ('zip', models.TextField(default='Zip')),
            ],
        ),
        migrations.CreateModel(
            name='HelpingLostPets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.TextField(default='Age')),
                ('breed', models.TextField(default='Breed')),
                ('color', models.TextField(default='Color')),
                ('date', models.TextField(default='Date')),
                ('gender', models.TextField(default='Gender')),
                ('image', models.TextField(default='Image')),
                ('location', models.TextField(default='Location')),
                ('name', models.TextField(default='Name')),
                ('petid', models.TextField(default='PetID')),
                ('size', models.TextField(default='Size')),
                ('status', models.TextField(default='Status')),
                ('zip', models.TextField(default='Zip')),
            ],
        ),
        migrations.CreateModel(
            name='imageReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LostMyDoggie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.TextField(default='Age')),
                ('breed', models.TextField(default='Breed')),
                ('color', models.TextField(default='Color')),
                ('date', models.TextField(default='Date')),
                ('gender', models.TextField(default='Gender')),
                ('image', models.TextField(default='Image')),
                ('location', models.TextField(default='Location')),
                ('name', models.TextField(default='Name')),
                ('petid', models.TextField(default='PetID')),
                ('size', models.TextField(default='Size')),
                ('status', models.TextField(default='Status')),
                ('zip', models.TextField(default='Zip')),
            ],
        ),
        migrations.CreateModel(
            name='PawBoost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.TextField(default='Age')),
                ('breed', models.TextField(default='Breed')),
                ('color', models.TextField(default='Color')),
                ('date', models.TextField(default='Date')),
                ('gender', models.TextField(default='Gender')),
                ('image', models.TextField(default='Image')),
                ('location', models.TextField(default='Location')),
                ('name', models.TextField(default='Name')),
                ('petid', models.TextField(default='PetID')),
                ('size', models.TextField(default='Size')),
                ('status', models.TextField(default='Status')),
                ('zip', models.TextField(default='Zip')),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.TextField(default='Age')),
                ('breed', models.TextField(default='Breed')),
                ('city', models.TextField(default='City')),
                ('color', models.TextField(default='Color')),
                ('date', models.TextField(default='Date')),
                ('gender', models.TextField(default='Gender')),
                ('image', models.ImageField(upload_to='images/')),
                ('name', models.TextField(default='Name')),
                ('petid', models.TextField(default='PetID')),
                ('size', models.TextField(default='Size')),
                ('state', models.TextField(default='State')),
                ('status', models.TextField(default='Status')),
                ('zip', models.TextField(default='Zip')),
            ],
        ),
        migrations.CreateModel(
            name='PetKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.TextField(default='Age')),
                ('breed', models.TextField(default='Breed')),
                ('color', models.TextField(default='Color')),
                ('date', models.TextField(default='Date')),
                ('gender', models.TextField(default='Gender')),
                ('image', models.TextField(default='Image')),
                ('location', models.TextField(default='Location')),
                ('name', models.TextField(default='Name')),
                ('petid', models.TextField(default='PetID')),
                ('size', models.TextField(default='Size')),
                ('status', models.TextField(default='Status')),
                ('zip', models.TextField(default='Zip')),
            ],
        ),
        migrations.CreateModel(
            name='TabbyTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.TextField(default='Age')),
                ('breed', models.TextField(default='Breed')),
                ('color', models.TextField(default='Color')),
                ('date', models.TextField(default='Date')),
                ('gender', models.TextField(default='Gender')),
                ('image', models.TextField(default='Image')),
                ('location', models.TextField(default='Location')),
                ('name', models.TextField(default='Name')),
                ('petid', models.TextField(default='PetID')),
                ('size', models.TextField(default='Size')),
                ('status', models.TextField(default='Status')),
                ('zip', models.TextField(default='Zip')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date_joined')),
                ('date_login', models.DateTimeField(auto_now_add=True, verbose_name='date_login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
