# Generated by Django 3.0.7 on 2020-06-28 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FurFinderAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='imageReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.TextField()),
            ],
        ),
    ]
