# Generated by Django 3.0.6 on 2020-06-12 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FurFinderAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='age',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='pet',
            old_name='dob',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='pet',
            old_name='size',
            new_name='image',
        ),
    ]
