# Generated by Django 3.0.6 on 2020-07-22 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FurFinderAPI', '0004_auto_20200717_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petimage',
            name='image',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
