# Generated by Django 3.0.7 on 2020-06-29 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FurFinderAPI', '0004_auto_20200625_0417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='color',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='pet',
            old_name='image',
            new_name='location',
        ),
        migrations.AddField(
            model_name='pet',
            name='size',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pet',
            name='state',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pet',
            name='zip',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
