# Generated by Django 3.0.6 on 2020-07-15 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FurFinderAPI', '0005_auto_20200715_0055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='petid',
        ),
    ]
