# Generated by Django 3.0.6 on 2020-07-23 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FurFinderAPI', '0005_auto_20200722_0653'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='summary',
            field=models.TextField(default='N/A'),
        ),
    ]
