# Generated by Django 3.0.6 on 2020-07-26 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FurFinderAPI', '0006_pet_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='author',
            field=models.TextField(default='Author'),
        ),
    ]
