# Generated by Django 3.0.6 on 2020-07-15 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FurFinderAPI', '0006_remove_pet_petid'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='petid',
            field=models.TextField(default='PetID'),
        ),
    ]
