# Generated by Django 3.0.6 on 2020-07-15 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FurFinderAPI', '0007_pet_petid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='location',
        ),
        migrations.AddField(
            model_name='pet',
            name='city',
            field=models.TextField(default='City'),
        ),
        migrations.AddField(
            model_name='pet',
            name='state',
            field=models.TextField(default='State'),
        ),
    ]
