# Generated by Django 3.0.6 on 2020-07-15 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FurFinderAPI', '0005_auto_20200715_0137'),
        ('FurFinderAPI', '0008_auto_20200715_0111'),
    ]

    operations = [
    ]
