from django.db import models

class Pet(models.Model):
    name = models.TextField()
    id = models.PositiveIntegerField(primary_key=True)
    gender = models.TextField()
    size = models.TextField()
    date = models.TextField()
    age = models.TextField()
    state = models.TextField()
    zip = models.TextField()
    location = models.TextField()
    breed = models.TextField()
    image = models.TextField()
    islost = models.BooleanField(default=True)


class ReportedPets(models.Model):
    name = models.TextField()
    id = models.PositiveIntegerField(primary_key=True)
    gender = models.TextField()
    size = models.TextField()
    date = models.TextField()
    age = models.TextField()
    state = models.TextField()
    zip = models.TextField()
    location = models.TextField()
    breed = models.TextField()
    image = models.TextField()
    islost = models.BooleanField(default=True)

class FidoFinder(models.Model):
    age = models.TextField(default='Age')
    breed = models.TextField(default='Breed')
    color = models.TextField(default='Color')
    date = models.TextField(default='Date')
    gender = models.TextField(default='Gender')
    image = models.TextField(default='Image')
    location = models.TextField(default='Location')
    name = models.TextField(default='Name')
    petid = models.TextField(default='PetID')
    size = models.TextField(default='Size')
    status = models.TextField(default='Status')
    zip = models.TextField(default='Zip')

class HelpingLostPets(models.Model):
    age = models.TextField(default='Age')
    breed = models.TextField(default='Breed')
    color = models.TextField(default='Color')
    date = models.TextField(default='Date')
    gender = models.TextField(default='Gender')
    image = models.TextField(default='Image')
    location = models.TextField(default='Location')
    name = models.TextField(default='Name')
    petid = models.TextField(default='PetID')
    size = models.TextField(default='Size')
    status = models.TextField(default='Status')
    zip = models.TextField(default='Zip')

class LostMyDoggie(models.Model):
    age = models.TextField(default='Age')
    breed = models.TextField(default='Breed')
    color = models.TextField(default='Color')
    date = models.TextField(default='Date')
    gender = models.TextField(default='Gender')
    image = models.TextField(default='Image')
    location = models.TextField(default='Location')
    name = models.TextField(default='Name')
    petid = models.TextField(default='PetID')
    size = models.TextField(default='Size')
    status = models.TextField(default='Status')
    zip = models.TextField(default='Zip')

class PawBoost(models.Model):
    age = models.TextField(default='Age')
    breed = models.TextField(default='Breed')
    color = models.TextField(default='Color')
    date = models.TextField(default='Date')
    gender = models.TextField(default='Gender')
    image = models.TextField(default='Image')
    location = models.TextField(default='Location')
    name = models.TextField(default='Name')
    petid = models.TextField(default='PetID')
    size = models.TextField(default='Size')
    status = models.TextField(default='Status')
    zip = models.TextField(default='Zip')

class PetKey(models.Model):
    age = models.TextField(default='Age')
    breed = models.TextField(default='Breed')
    color = models.TextField(default='Color')
    date = models.TextField(default='Date')
    gender = models.TextField(default='Gender')
    image = models.TextField(default='Image')
    location = models.TextField(default='Location')
    name = models.TextField(default='Name')
    petid = models.TextField(default='PetID')
    size = models.TextField(default='Size')
    status = models.TextField(default='Status')
    zip = models.TextField(default='Zip')

class TabbyTracker(models.Model):
    age = models.TextField(default='Age')
    breed = models.TextField(default='Breed')
    color = models.TextField(default='Color')
    date = models.TextField(default='Date')
    gender = models.TextField(default='Gender')
    image = models.TextField(default='Image')
    location = models.TextField(default='Location')
    name = models.TextField(default='Name')
    petid = models.TextField(default='PetID')
    size = models.TextField(default='Size')
    status = models.TextField(default='Status')
    zip = models.TextField(default='Zip')